spring.application.name=my-market-app

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

logging.level.org.springframework.web=DEBUG

spring.cache.type=redis

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.r2dbc.url=r2dbc:h2:mem:///memdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.r2dbc.username=sa
spring.r2dbc.password=

spring.r2dbc.init.mode=always
spring.r2dbc.init.schema-locations=classpath:schema.sql
spring.r2dbc.init.data-locations=classpath:data.sql

spring.security.oauth2.client.registration.paymentservice.client-id=mymarketapp
spring.security.oauth2.client.registration.paymentservice.client-secret=msUyIK0UDCVCAdBrtR0apqUeysGfuUIA
spring.security.oauth2.client.registration.paymentservice.authorization-grant-type=client_credentials
spring.security.oauth2.client.provider.paymentservice.token-uri=http://localhost:8082/realms/master/protocol/openid-connect/token