spring.application.name=my-market-app

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

logging.level.org.springframework.web=DEBUG
logging.level.org.thymeleaf=DEBUG

spring.datasource.url=jdbc:h2:mem:memdb;
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql